<?php

namespace common\models\Queries;

/**
 * This is the ActiveQuery class for [[\common\models\RecipeCategories]].
 *
 * @see \common\models\RecipeCategories
 */
class RecipeCategoriesQuery extends \common\components\BaseActiveQuery
{
    /*public function active()
    {
        return $this->andWhere('[[status]]=1');
    }*/

    /**
     * @inheritdoc
     * @return \common\models\RecipeCategories[]|array
     */
    public function active()
    {
        return $this->andWhere(['recipe_categories.active'=>1]); // TODO: Change the autogenerated stub
    }

    public function all($db = null)
    {
        return parent::all($db);
    }

    /**
     * @inheritdoc
     * @return \common\models\RecipeCategories|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }
}
